### ISSUE TITLE
Scala 2.11 support/AWS EMR compatibility

### ISSUE THREAD

**Issue by Liam3851** [seratch/AWScala#216]
Thanks very much for AWScala! This project has been a big help to me.

I noticed that Maven has no artifact for 0.8.4 for Scala 2.11-- it appears dropping 2.11 was part of #215. Unfortunately AWS EMR still only supports Scala 2.11 (EMR has a beta of Spark on Scala 2.12, EMR 6.0.0 beta 2, but that has not yet been released to production yet), so this means AWScala 0.8.4 (with the recent SDK version bumps) cannot be used in Spark jobs on EMR.

I came across this because running an sbt assembly built with AWScala 0.8.3 in Spark on an EMR cluster with EMR 5.28.0+, using Glue as a Hive metastore, can fail with NoClassDefFoundError, because the version of the AWS SDK linked with AWScala  (1.11.621) are too far off from the version of the AWS SDK that comes on the server (1.11.659 (EMR 5.28) and 1.11.682 (EMR 5.29)).

For now my workaround is to explicitly link the more-advanced AWS SDK version from the server in my sbt assembly, and let the explicit newer version evict AWScala's dependency. This gets rid of the NoClassDefFoundError and seems to make things work. If this should work I'm totally fine doing it, and retaining 0.8.3 as the final Scala 2.11 version is probably fine.

However, I've been hesitant to deploy this workaround to prod because I'm unsure of the strength of AWScala's dependency on a particular Java SDK version. #179 proposed marking the Java SDK provided with a minimum version, and allowing users to link in newer versions, but it's not totally clear to me that that would actually work safely. Is it generally safe to link a later version of the AWS Java SDK to a version of AWScala that depends on an earlier version?

**Comment by seratch** [comment]
>Is it generally safe to link a later version of the AWS Java SDK to a version of AWScala that depends on an earlier version?

It depends but it may not be safe for some cases. The AWS Java SDK releases are not binary-compatible even among patch versions. So, linking a different version can be a cause of runtime errors.

I don't want to have cross builds with Scala 2.11 for this entire project anymore. But you have the necessity to have scala 2.11 builds specifically for the EMR module, I'm open to the idea to ship scala 2.11 builds only for it. The cross-build won't be so complex probably. Personally, I don't have much time to spend on it. I would like to have some contributions on it from the user community.

**Comment by Liam3851** [comment]
I can't speak to other users, but the parts of AWScala I use on EMR primarily are the SQS module and the S3 module.. the EMR module itself is mostly for starting/managing clusters (which I do on machines that aren't themselves EMR clusters); once I'm on the cluster I don't really need the EMR submodule anymore.

That said, I understand the desire not to manage cross-builds esp. for a version of Scala now two revisions out of date and deprecated even for Spark.

I'm not super-familiar with the internals of AWScala or its build procedure, but if I were to fork and then revert to the build code to the code prior to #215, how hard would it be for me to build a custom 2.11-compatible artifact against the newer Java SDK?

**Comment by Liam3851** [comment]
EMR from version 6.0.0 supports Scala 2.12. Closing.
